extern int conn;
extern int start(int);
extern int acceptConnection();
extern int * getClients();
extern int ban();
extern int kick();
extern int sendMessage(int, char*);
extern int pingClient(int);
extern int broadcast(int*, int, char*);
extern char * receiveMessage();
