extern int serverAccept();
extern int serverBanAddress(char*);
extern int serverBanCheckClient(int);
extern int serverBanClient(int);
extern int serverBroadcast(char*);
extern int * serverClients();
extern int serverCloseAll();
extern int serverClose(int);
extern char * serverGetClientAddress(int);
extern int serverSend(int, char*);
extern int serverStart(int);
extern int serverPingAll();
extern int serverPing(int);
extern char * serverReceive(int);
extern char * serverReceiveAny();